obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  device_info/


#ifdefine OPLUS_ARCH_EXTENDS
#GaoTing.Gan@PSW.MultiMedia.MediaServer, 2019/03/07, Add for kevent feedback
obj-y +=  oppo_kevent_feedback/
#endif /* OPLUS_ARCH_EXTENDS */
