#  ifdef OPLUS_ARCH_EXTENDS
#GaoTing.Gan@PSW.MultiMedia.MediaServer, 2019/03/07, Add for kevent feedback
#obj-$(CONFIG_OPPO_CRITICALLOG)	+=  oppo_kevent_feedback.o
obj-y	+=  oppo_kevent_feedback.o
#  endif /* OPLUS_ARCH_EXTENDS */
