#ifdef OPLUS_FEATURE_HEALTHINFO
#/* Huacai.Zhou@PSW.BSP.Kernel.MM, 2018-07-07, add alloc wait monitor support*/
obj-$(CONFIG_OPPO_MEM_MONITOR) += memory_monitor.o
#endif /* OPLUS_FEATURE_HEALTHINFO */

