#Zhao.Pan@MULTIMEDIA.AUDIODRIVER.KERNEL, 2020/08/08, Add for multimedia kevent feedback driver
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK)	+= oplus_mm_kevent.o
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK)	+= oplus_mm_kevent_fb.o
