#ifdef OPLUS_FEATURE_HEALTHINFO
#wenbin.liu@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
#obj-$(CONFIG_OPPO_HEALTHINFO)	+=  oppo_healthinfo.o
obj-$(CONFIG_OPPO_HEALTHINFO)  +=  oppo_healthinfo.o
#endif /* OPLUS_FEATURE_HEALTHINFO */
